#!/usr/bin/env bash

PARAMS=$*

if [ "$PARAMS" == "" ]; then
    echo -e "Please provide a commit message!"
    exit 1
fi

git add .
if ! git commit -S -m "$PARAMS"; then
    echo -e "Failed to sign commit, using unsigned commit instead."
    if ! git commit -S -m "$PARAMS"; then
        echo -e "Failed to commit, aborting."
    fi
fi
