#!/usr/bin/env bash

PARAMS=$*

if [ "$PARAMS" == "" ]; then
    echo -e "Please provide a commit message!"
    exit 1
fi

if ! git add .; then
    echo -e "Failed to add all changes, aborting."
    exit 1
fi

if ! git commit -S -m "$PARAMS"; then
    echo -e "Failed to sign commit, using unsigned commit instead."
    if ! git commit -S -m "$PARAMS"; then
        echo -e "Failed to commit, aborting."
        exit 1
    fi
fi
