#!/usr/bin/env bash

PARAMS=$*
PORT=80

if [ "$PARAMS" != "" ]; then
    sudo python3 -m http.server $PARAMS
else
    echo -e "No port provided, using default port $PORT"
    sudo python3 -m http.server $PORT
fi
