#!/usr/bin/env bash

# - Colours -------------------------------------------------------------------

COL_RED='\033[0;31m'
COL_CLEAR='\033[0m'
COL_YELLOW='\033[1;33m'

# - Root permissions ----------------------------------------------------------

SUDO="sudo"
function trysudo() {
    BIN=$1
    SYNTAX=$2
    [ "$SYNTAX" == "" ] && SYNTAX="-h"

    $BIN "$SYNTAX" &> /dev/null
    return $?
}
if trysudo "sudo"; then
    SUDO="sudo"
elif trysudo "doas"; then
    SUDO="doas"
else
    echo -e "${COL_RED}This program only supports sudo and doas. Please install one of these to continue.${COL_CLEAR}"
    exit 1
fi


# - Repositories --------------------------------------------------------------

COMMANDS=()
function cmd() {
    IS_SUDO=$1
    BIN=$2
    SYNTAX=$3
    VERSION_CMD=$4
    [ "$VERSION_CMD" == "" ] && VERSION_CMD="-v"

    # Return, if binary not found:
    if ! $BIN "$VERSION_CMD" &> /dev/null; then
        return 0
    fi

    PREFIX=""
    [ "$IS_SUDO" == "x" ] && PREFIX="$SUDO "

    COMMANDS+=( "$PREFIX$BIN $SYNTAX" )
}

# System repositories:
cmd x "pacman"   "-Syu"                  # Arch-Linux
cmd o "yay"      "-Syu"                  # Arch-Linux
cmd x "apt"      "update"   "help"       # Debian
cmd x "apt"      "upgrade"  "help"       # Debian
cmd x "zypper"   "up"       "help"       # OpenSUSE
cmd x "dnf"      "upgrade"  "--version"  # RedHat

# Additional repositories:
cmd o "flatpak"  "update"   "--help"
cmd x "snap"     "refresh"  "help"

# Additional updaters:
cmd o "gitman"   "pull"     "help"


# - Execution -----------------------------------------------------------------

echo -e "${COL_YELLOW}The following commands will be executed:${COL_CLEAR}"
for COMMAND in "${COMMANDS[@]}"; do
    echo -e "\t$COMMAND"
done

printf "\nContinue? [Y/n] "
read -r CONTINUE
case "$CONTINUE" in
    N|n)
        echo -e "Aborting..."
        exit 1
        ;;
    *)
        echo -e "Continuing...\n"
        ;;
esac

for COMMAND in "${COMMANDS[@]}"; do
    echo -e "${COL_YELLOW}Executing '$COMMAND'${COL_CLEAR}"
    $COMMAND
done
echo -e "${COL_YELLOW}Update completed!${COL_CLEAR}"
